apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oc-client-example
commonLabels:
  app: oc-client-example
resources:
- serviceaccount.yaml
- role.yaml
- rolebinding.yaml
- deployment.yaml
- cronjob-down.yaml
- cronjob-up.yaml
