kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oc-client-role
rules:
  - verbs:
      - get
      - list
      - create
      - watch
      - patch
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - list
      - create
      - watch
      - patch
    apiGroups:
      - 'apps'
    resources:
      - deployments
      - deployments/scale
